# Generated by Django 6.1 on 2026-08-07 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(help_text="Shown on cards, e.g. 'A gathering of tech innovators...'", max_length=250)),
                ('description', models.TextField(help_text='Longer paragraph shown on the event detail page.')),
                ('image', models.ImageField(upload_to='events/')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('engagement', 'Engagement'), ('birthday', 'Birthday party'), ('baby_shower', 'Baby Shower'), ('corporate', 'Corprate Event')], default='corporate', max_length=30)),
                ('budget_range', models.CharField(choices=[('below_50000', 'Below-50,000'), ('50000_100000', '50,000-100000'), ('100000_200000', '100000-200000'), ('200000_500000', '200000-500000'), ('above_500000', 'Above-500000')], default='below_50000', max_length=30)),
                ('location', models.CharField(choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('coimbatore', 'Coimbatore'), ('madurai', 'Madurai'), ('salem', 'Salem')], default='chennai', max_length=30)),
                ('venue', models.CharField(choices=[('banquet_hall', 'Banquet Hall'), ('convention_center', 'Convention Center'), ('outdoor_open_ground', 'Outdoor / Open Ground'), ('beach_resort', 'Beach / resort'), ('hotel', 'Hotel')], default='banquet_hall', max_length=30)),
                ('services_included', models.TextField(blank=True, default='Keynote Speakers\nInteractive Workshops\nNetworking Events\nExhibition Hall', help_text='One service per line.')),
                ('highlight_attendees', models.CharField(blank=True, default='500+ Attendees', max_length=50)),
                ('highlight_speakers', models.CharField(blank=True, default='30+ Speakers', max_length=50)),
                ('highlight_duration', models.CharField(blank=True, default='2-Day Event', max_length=50)),
                ('highlight_venue', models.CharField(blank=True, default='Downtown Convention Center', max_length=80)),
                ('pricing_note', models.TextField(blank=True, default='Pricing varies based on the services selected and the scale of the event. Contact us for a detailed quote tailored to your specific needs.')),
                ('phone_number', models.CharField(blank=True, default='+1-555-123-4567', max_length=30)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured events show up in the homepage Events Preview.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('calendar', 'Calendar'), ('palette', 'Palette'), ('users', 'Users'), ('megaphone', 'Megaphone'), ('clock', 'Clock'), ('wallet', 'Wallet')], default='calendar', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Make Events', max_length=100)),
                ('company_name', models.CharField(default='Master Promote', max_length=100)),
                ('hero_title', models.CharField(default='Every Event Memorable & Stress-Free', max_length=200)),
                ('hero_subtitle', models.CharField(default='We plan, design, and manage unforgettable events with professional execution and creative excellence.', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_story', models.TextField(blank=True, default='')),
                ('about_mission', models.TextField(blank=True, default='')),
                ('years_of_experience', models.PositiveIntegerField(default=14)),
                ('about_team_intro', models.TextField(blank=True, default='')),
                ('phone', models.CharField(default='+1-555-123-4567', max_length=30)),
                ('email', models.EmailField(default='info@masterpromote.com', max_length=254)),
                ('office_address', models.CharField(default='123 Event Avenue, Cityville, State 12345', max_length=200)),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('facebook_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('message', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('star', 'Star'), ('shield', 'Shield'), ('users', 'Users'), ('clock', 'Clock')], default='star', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Choose Us Card',
                'verbose_name_plural': 'Why Choose Us Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About - Why Choose Us Card',
                'verbose_name_plural': 'About - Why Choose Us Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('engagement', 'Engagement'), ('birthday', 'Birthday party'), ('baby_shower', 'Baby Shower'), ('corporate', 'Corprate Event')], max_length=30)),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
